Update myservice

diff --git a/snippets/service/myservice b/snippets/service/myservice
--- a/snippets/service/myservice
+++ b/snippets/service/myservice
@@ -5,3 +5,92 @@
 #Modified Date:
 #Author: muslih k
 # START #
+
+appname=myapp
+directory=/home/muslih/myapplication
+execu=$directory/myapp.py
+pid=$directory/myapp.pid
+logfile=$directory/myapp.log
+
+
+RED='\033[0;31m'
+GR='\033[0;32m'
+YL='\033[0;33m'
+NC='\033[0m' # No Color
+
+source ~/.bashrc
+
+case "$1" in
+start)
+
+   if [ -e "$pid" ];then
+        if [[ "$(ps -aux | grep `cat $pid` |grep -c $execu)" -eq 1 ]]; then
+          echo 0:$appname is already running, on pid=`cat $pid`
+          printf "${YL}[Already Running]${NC} \n"
+          exit 1
+        fi
+   fi
+   echo $appname is starting..
+   echo "start on" $(date) >> $logfile
+   python3 $execu >> $logfile 2>&1 &
+   pidval=$!
+   echo $pidval
+   sleep 1
+   if [[ "$(ps -aux | grep $pidval |grep -c $execu)" -eq 1 ]]; then
+          touch $pid
+          echo $pidval>$pid
+          echo 1:$appname is started, on pid=`cat $pid`
+          printf "${GR}[Started]${NC}\n"
+          exit 0
+   else
+          echo 0:$appname is NOT started
+          printf "${RED}[FAILED]${NC}\n"
+          rm -f $pid
+          exit 1
+   fi
+   ;;
+stop)
+
+   if [ -e "$pid" ];then
+        if [[ "$(ps -aux | grep `cat $pid` |grep -c $execu)" -eq 1 ]]; then
+                echo $appname is stoping...
+                kill `cat $pid`
+                rm -f $pid
+                printf "${RED}[Stoped]${NC}\n"
+                exit 0
+        else
+                echo 0:$appname is NOT running
+                printf "${RED}[Inactive]${NC}\n"
+                rm -f $pid
+                exit 0
+        fi
+   else
+        echo 0:$appname is NOT running
+        printf "${RED}[Inactive]${NC}\n"
+   fi
+   ;;
+restart)
+   $0 stop
+   $0 start
+   ;;
+status)
+   if [ -e "$pid" ];then
+        if [[ "$(ps -aux | grep `cat $pid` |grep -c $execu)" -eq 1 ]]; then
+        echo 1:$appname is running, pid=`cat $pid`
+        printf "${GR}[Active]${NC}\n"
+        else
+        echo 0:$appname is NOT running
+        printf "${RED}[Inactive]${NC}\n"
+        rm -f $pid
+        exit 1
+        fi
+   else
+        echo 0:$appname is NOT running
+        printf "${RED}[Inactive]${NC}\n"
+   fi
+   ;;
+*)
+   echo "Usage: $0 {start|stop|status|restart}"
+esac
+
+exit 0
